In [30]:
import requests

headers = {'User-Agent': 'Plant Watering Reminder App | https://github.com/Murphy96/Plant_Watering_Reminder | murphybovbjerg@gmail.com'}

zone_id = 'NC025'
start_date = '2026-08-27T23%3A00%3A00Z'
end_date = '2026-08-28T00%3A00%3A01Z'

endpoint = f'https://api.weather.gov/zones/forecast/{zone_id}/observations?start={start_date}&end={end_date}&limit=500'


response = requests.get(endpoint, headers = headers)
response.raise_for_status()
data = response.json()




#def get_weekly_weather (start_time, end_time, limit, nws_zone): 
    #response = requests.get(https://api.weather.gov/zones/forecast/CAZ043/observations?start=2026-08-20T00%3A00%3A00Z&end=2026-08-28T00%3A00%3A00Z&limit=500)

HTTPError: 404 Client Error: Not Found for url: https://api.weather.gov/zones/forecast/NC025/observations?start=2026-08-27T23%3A00%3A00Z&end=2026-08-28T00%3A00%3A01Z&limit=500

In [29]:
data['features']

KeyError: 'features'

In [15]:
import pandas as pd
observations = []

for observation in data['features']:
    properties = observation['properties']

    observations.append({
        'station_id': properties['stationId'],
        'station_name': properties['stationName'],
        'timestamp': properties['timestamp'],
        'temperature': properties['temperature']['value'],
        'max_temperature_24h': properties['maxTemperatureLast24Hours']['value'],
        'min_temperature_24h': properties['minTemperatureLast24Hours']['value'], 
        'precipitation_last_3_hours': properties['precipitationLast3Hours']['value']
    })

df = pd.DataFrame(observations)

df

,station_id,station_name,timestamp,temperature,max_temperature_24h,min_temperature_24h,precipitation_last_3_hours
0,D5683,DW5683 Rocklin,2026-08-28T00:00:00+00:00,36.11,None,None,None
1,E3174,EW3174 Oceanside,2026-08-28T00:00:00+00:00,25.00,None,None,None
2,E3218,EW3218 ORO VALLEY,2026-08-28T00:00:00+00:00,38.89,None,None,None
3,E3219,EW3219 National City,2026-08-28T00:00:00+00:00,26.67,None,None,None
4,E3680,EW3680 Lemon Grove,2026-08-28T00:00:00+00:00,30.56,None,None,None
...,...,...,...,...,...,...,...
121,KCRQ,"Carlsbad, McClellan-Palomar Airport",2026-08-27T23:00:00+00:00,30.00,None,None,None
122,KMYF,"San Diego, Montgomery Field",2026-08-27T23:00:00+00:00,31.00,None,None,None
123,KOKB,"Oceanside, Oceanside Municipal Airport",2026-08-27T23:00:00+00:00,31.00,None,None,None
124,KSAN,San Diego International Airport,2026-08-27T23:00:00+00:00,28.00,None,None,None
125,KSDM,"San Diego, Brown Field Municipal Airport",2026-08-27T23:00:00+00:00,29.00,None,None,None

In [10]:
df['station_id'].nunique

<bound method IndexOpsMixin.nunique of 0       KCRQ
1       KMYF
2       KNKX
3       KOKB
4       KSAN
       ...
495    F0495
496    F6395
497     KCRQ
498     KMYF
499     KOKB
Name: station_id, Length: 500, dtype: str>

In [21]:
df.sort_values(by='timestamp', ascending=True)
df

,station_id,station_name,timestamp,temperature,max_temperature_24h,min_temperature_24h,precipitation_last_3_hours
0,D5683,DW5683 Rocklin,2026-08-28T00:00:00+00:00,36.11,None,None,None
1,E3174,EW3174 Oceanside,2026-08-28T00:00:00+00:00,25.00,None,None,None
2,E3218,EW3218 ORO VALLEY,2026-08-28T00:00:00+00:00,38.89,None,None,None
3,E3219,EW3219 National City,2026-08-28T00:00:00+00:00,26.67,None,None,None
4,E3680,EW3680 Lemon Grove,2026-08-28T00:00:00+00:00,30.56,None,None,None
...,...,...,...,...,...,...,...
121,KCRQ,"Carlsbad, McClellan-Palomar Airport",2026-08-27T23:00:00+00:00,30.00,None,None,None
122,KMYF,"San Diego, Montgomery Field",2026-08-27T23:00:00+00:00,31.00,None,None,None
123,KOKB,"Oceanside, Oceanside Municipal Airport",2026-08-27T23:00:00+00:00,31.00,None,None,None
124,KSAN,San Diego International Airport,2026-08-27T23:00:00+00:00,28.00,None,None,None
125,KSDM,"San Diego, Brown Field Municipal Airport",2026-08-27T23:00:00+00:00,29.00,None,None,None

In [24]:
filtered_df = df.loc[df['max_temperature_24h'] != 'None']
filtered_df

,station_id,station_name,timestamp,temperature,max_temperature_24h,min_temperature_24h,precipitation_last_3_hours
0,D5683,DW5683 Rocklin,2026-08-28T00:00:00+00:00,36.11,None,None,None
1,E3174,EW3174 Oceanside,2026-08-28T00:00:00+00:00,25.00,None,None,None
2,E3218,EW3218 ORO VALLEY,2026-08-28T00:00:00+00:00,38.89,None,None,None
3,E3219,EW3219 National City,2026-08-28T00:00:00+00:00,26.67,None,None,None
4,E3680,EW3680 Lemon Grove,2026-08-28T00:00:00+00:00,30.56,None,None,None
...,...,...,...,...,...,...,...
121,KCRQ,"Carlsbad, McClellan-Palomar Airport",2026-08-27T23:00:00+00:00,30.00,None,None,None
122,KMYF,"San Diego, Montgomery Field",2026-08-27T23:00:00+00:00,31.00,None,None,None
123,KOKB,"Oceanside, Oceanside Municipal Airport",2026-08-27T23:00:00+00:00,31.00,None,None,None
124,KSAN,San Diego International Airport,2026-08-27T23:00:00+00:00,28.00,None,None,None
125,KSDM,"San Diego, Brown Field Municipal Airport",2026-08-27T23:00:00+00:00,29.00,None,None,None

In [25]:
df['max_temperature_24h'].unique()

array([None], dtype=object)

In [31]:
import requests

url = "https://www.ncei.noaa.gov/pub/has/HAS012738957/0001/asos-5min-KRDU-202608.dat"

response = requests.get(url)
response.raise_for_status()

with open("asos-5min-KRDU-202608.dat", "wb") as f:
    f.write(response.content)